### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by robertbaker**
@Admin9705 

This properly fixes the issues that the last PR I made addresses without changing the PG defaults to the rclone defaults.

This PR includes:
Better option descriptions and help text.
Ability to set "offable" options to "off" by using 0 for those options.
changes the vars so they store the sizeSuffix in the var, which makes "off" able to be an option, and allows further flexibility in the future.

This PR does not change the PG defaults to match the rclone defaults, so existing users should not notice a difference. There's one Cavet. In the past if you are using encryption, cache mode for the crypt mount was forced to "writes". Unencrypt mounts were forced to "off".

This PR allows the cache mode to be customizable, and therefore sets "off" by default. This may affect users in some cases, but they can just change the the cache mode to "writes". I recommend the cache mode set to "writes" for the best compatibility with all PG community apps, but that would be changing the defaults previously used.

### CODE REVIEW

**Comment by robertbaker** [comment]
@MrDoobPG  please test this!

**Comment by Admin9705** [comment]
Before accepted, we should test and accept after some time with the 429 issues from Google not compound anything. Probably rewrite this for 8.7

**Comment by Admin9705** [comment]
Also I wanted to build an input checker, like if it's a bad value, for e reset to default.

**Comment by robertbaker** [comment]
@Admin9705 I've added a input validation check to ensure only integers are entered.

**Pull request closed without merging**
